AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  Exclude:
    - "Formula/**/*"
    - "vendor/**/*"

# Metrics - relax thresholds for this small CLI tool
Metrics/AbcSize:
  Max: 35

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Metrics/ClassLength:
  Max: 300

# Gemspec
Gemspec/DevelopmentDependencies:
  Enabled: false

# Style
Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false
